"use client";

import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface ReportData {
  code: string; title: string; sample: string; product: string;
  batch: string; client: string; type: string; status: string;
  result: string | null; resultStatus: string | null;
  method: string | null; created: string;
}

export function PdfExportButton({ report }: { report: ReportData }) {
  function exportPdf() {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const width = doc.internal.pageSize.getWidth();

    // Header band
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, width, 72, "F");
    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("PharmaLIMS", 40, 34);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("GMP-compliant pharmaceutical testing laboratory", 40, 50);

    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(report.title, 40, 108);

    autoTable(doc, {
      startY: 124,
      theme: "grid",
      headStyles: { fillColor: [241, 245, 249], textColor: [51, 65, 85] },
      styles: { fontSize: 9, cellPadding: 5 },
      head: [["Field", "Value"]],
      body: [
        ["Report number", report.code],
        ["Sample", report.sample],
        ["Product", report.product],
        ["Batch", report.batch],
        ["Client", report.client],
        ["Test type", report.type],
        ["Analytical method", report.method ?? "—"],
        ["Result", report.result ?? "—"],
        ["Specification status", report.resultStatus ?? "—"],
        ["Report date", report.created],
      ],
    });

    const y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 400;

    // Signature block
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("Authorized by", 40, y + 36);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(79, 70, 229);
    doc.text("Digitally signed — PharmaLIMS QA", 40, y + 54);

    doc.setTextColor(120, 130, 145);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(
      `Report ${report.code} · Status: ${report.status} · Generated by PharmaLIMS audit-controlled reporting`,
      40,
      doc.internal.pageSize.getHeight() - 32,
    );

    doc.save(`${report.code}.pdf`);
  }

  return (
    <Button size="sm" variant="secondary" onClick={exportPdf} title="Download PDF">
      <Download className="h-3.5 w-3.5" /> PDF
    </Button>
  );
}